# Development environment

FROM ubuntu:groovy-20210325.1

# Install software
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get -y install nginx memcached nano php php-memcached php-curl php-json php-mbstring php-dom php-yaml cron
RUN apt-get -y install nano
#RUN apt-get clean

# Create directories
RUN rm -Rf /var/www/html/*
RUN mkdir /var/www/html/webroot
RUN mkdir /var/www/html/scripts
RUN mkdir /var/www/html/engine

# Copy in configurations
COPY ./docker/conf/site.conf /etc/nginx/sites-enabled/default
COPY ./docker/scripts/run.sh /var/www/html/run.sh
#COPY ./webroot /var/www/html/webroot

WORKDIR /var/www/html
VOLUME /var/www/html/webroot
VOLUME /var/www/html/engine

# Set up extra dev stuff
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Listen here
EXPOSE 80

CMD ["/var/www/html/run.sh"]